
# ==============================================
# MASTER 3,500+ US STOCK UNIVERSE (HARDCODED GUARANTEE)
# ==============================================
MASTER_3500_UNIVERSE = [
    "A",
    "AA",
    "AAAU",
    "AAC",
    "AACB",
    "AACG",
    "AACI",
    "AACO",
    "AACP",
    "AADX",
    "AAGH",
    "AAL",
    "AAME",
    "AAMI",
    "AAOI",
    "AAON",
    "AAP",
    "AAPG",
    "AAPI",
    "AAPL",
    "AAQL",
    "AARD",
    "AASP",
    "AAT",
    "AATC",
    "AAUC",
    "AAWH",
    "AB",
    "ABAT",
    "ABBV",
    "ABCB",
    "ABCL",
    "ABCP",
    "ABEO",
    "ABEV",
    "ABG",
    "ABIT",
    "ABLV",
    "ABM",
    "ABNB",
    "ABOS",
    "ABPO",
    "ABR",
    "ABSI",
    "ABT",
    "ABTC",
    "ABTS",
    "ABUS",
    "ABVC",
    "ABVX",
    "ABX",
    "ABXL",
    "ACA",
    "ACAA",
    "ACAD",
    "ACAT",
    "ACB",
    "ACBM",
    "ACCL",
    "ACCO",
    "ACCS",
    "ACDC",
    "ACEL",
    "ACET",
    "ACFN",
    "ACGC",
    "ACGL",
    "ACGP",
    "ACH",
    "ACHC",
    "ACHR",
    "ACHV",
    "ACI",
    "ACIC",
    "ACIU",
    "ACIW",
    "ACLS",
    "ACM",
    "ACMR",
    "ACN",
    "ACNB",
    "ACNT",
    "ACOG",
    "ACON",
    "ACP",
    "ACR",
    "ACRE",
    "ACRG",
    "ACRL",
    "ACRS",
    "ACRV",
    "ACT",
    "ACTG",
    "ACTU",
    "ACU",
    "ACUT",
    "ACV",
    "ACVA",
    "ACXP",
    "AD",
    "ADAC",
    "ADAG",
    "ADAM",
    "ADBE",
    "ADBT",
    "ADC",
    "ADCT",
    "ADEA",
    "ADGM",
    "ADI",
    "ADIA",
    "ADIG",
    "ADIL",
    "ADM",
    "ADMA",
    "ADMG",
    "ADMQ",
    "ADMT",
    "ADNH",
    "ADNT",
    "ADP",
    "ADPT",
    "ADSE",
    "ADSK",
    "ADT",
    "ADTI",
    "ADTN",
    "ADTX",
    "ADUR",
    "ADUS",
    "ADV",
    "ADVB",
    "ADX",
    "ADXN",
    "AEAE",
    "AEAQ",
    "AEBI",
    "AEC",
    "AEE",
    "AEF",
    "AEFC",
    "AEG",
    "AEHL",
    "AEHR",
    "AEI",
    "AEIS",
    "AEM",
    "AEMD",
    "AENT",
    "AEO",
    "AEON",
    "AER",
    "AERA",
    "AERG",
    "AERO",
    "AERT",
    "AES",
    "AESI",
    "AESP",
    "AETN",
    "AEVA",
    "AEXA",
    "AEYE",
    "AFB",
    "AFBI",
    "AFCG",
    "AFG",
    "AFGB",
    "AFGC",
    "AFGD",
    "AFGE",
    "AFJK",
    "AFL",
    "AFRI",
    "AFRM",
    "AFYA",
    "AG",
    "AGBK",
    "AGCC",
    "AGCO",
    "AGD",
    "AGEN",
    "AGGI",
    "AGI",
    "AGIG",
    "AGIO",
    "AGL",
    "AGLY",
    "AGM",
    "AGMB",
    "AGMH",
    "AGNC",
    "AGNT",
    "AGO",
    "AGPU",
    "AGQ",
    "AGRO",
    "AGRZ",
    "AGSS",
    "AGTX",
    "AGX",
    "AGYS",
    "AHCO",
    "AHG",
    "AHII",
    "AHMA",
    "AHR",
    "AHRO",
    "AHRT",
    "AHT",
    "AI",
    "AIAI",
    "AIB",
    "AIBT",
    "AIBZ",
    "AIDX",
    "AIEV",
    "AIFA",
    "AIFC",
    "AIFF",
    "AIFU",
    "AIG",
    "AIHS",
    "AII",
    "AIIA",
    "AIIO",
    "AIIR",
    "AIM",
    "AIMD",
    "AIN",
    "AIO",
    "AIOS",
    "AIOT",
    "AIP",
    "AIQD",
    "AIQU",
    "AIR",
    "AIRE",
    "AIRG",
    "AIRI",
    "AIRJ",
    "AIRO",
    "AIRS",
    "AIRT",
    "AISP",
    "AIT",
    "AITX",
    "AIV",
    "AIXC",
    "AIXI",
    "AIXN",
    "AIZ",
    "AIZN",
    "AJG",
    "AKA",
    "AKAM",
    "AKAN",
    "AKBA",
    "AKR",
    "AKTS",
    "AKTX",
    "ALAB",
    "ALAR",
    "ALB",
    "ALBC",
    "ALC",
    "ALCE",
    "ALCO",
    "ALDA",
    "ALDF",
    "ALDS",
    "ALDX",
    "ALEC",
    "ALF",
    "ALG",
    "ALGM",
    "ALGN",
    "ALGS",
    "ALGT",
    "ALH",
    "ALHC",
    "ALIS",
    "ALIT",
    "ALK",
    "ALKS",
    "ALKT",
    "ALL",
    "ALLE",
    "ALLO",
    "ALLR",
    "ALLT",
    "ALLY",
    "ALM",
    "ALMP",
    "ALMR",
    "ALMS",
    "ALMU",
    "ALNT",
    "ALNY",
    "ALOT",
    "ALOV",
    "ALOY",
    "ALP",
    "ALPS",
    "ALPX",
    "ALRM",
    "ALRS",
    "ALSN",
    "ALT",
    "ALTB",
    "ALTG",
    "ALTI",
    "ALTO",
    "ALTX",
    "ALUB",
    "ALUR",
    "ALV",
    "ALVO",
    "ALX",
    "ALXO",
    "ALZN",
    "AM",
    "AMAC",
    "AMAL",
    "AMAN",
    "AMAT",
    "AMBA",
    "AMBO",
    "AMBP",
    "AMBQ",
    "AMBR",
    "AMC",
    "AMCI",
    "AMCR",
    "AMCX",
    "AMD",
    "AME",
    "AMFN",
    "AMG",
    "AMGN",
    "AMH",
    "AMIX",
    "AMJB",
    "AMKR",
    "AMLM",
    "AMLX",
    "AMN",
    "AMOD",
    "AMP",
    "AMPG",
    "AMPH",
    "AMPL",
    "AMPM",
    "AMPX",
    "AMPY",
    "AMR",
    "AMRC",
    "AMRN",
    "AMRX",
    "AMRZ",
    "AMS",
    "AMSC",
    "AMSF",
    "AMSS",
    "AMST",
    "AMT",
    "AMTB",
    "AMTD",
    "AMTM",
    "AMTU",
    "AMTX",
    "AMUB",
    "AMWL",
    "AMX",
    "AMZE",
    "AMZN",
    "AN",
    "ANAB",
    "ANDE",
    "ANDG",
    "ANEB",
    "ANET",
    "ANF",
    "ANGH",
    "ANGI",
    "ANGO",
    "ANGX",
    "ANIK",
    "ANIP",
    "ANIX",
    "ANKM",
    "ANL",
    "ANNA",
    "ANNX",
    "ANPA",
    "ANRO",
    "ANSC",
    "ANTA",
    "ANTX",
    "ANVI",
    "ANVS",
    "ANY",
    "AOAO",
    "AOD",
    "AOMD",
    "AOMN",
    "AOMR",
    "AON",
    "AORT",
    "AOS",
    "AOSL",
    "AOUT",
    "AOXY",
    "AP",
    "APA",
    "APAC",
    "APAM",
    "APBD",
    "APC",
    "APCX",
    "APD",
    "APEI",
    "APG",
    "APGE",
    "APGH",
    "APH",
    "APHD",
    "APHP",
    "API",
    "APLD",
    "APLE",
    "APLM",
    "APMC",
    "APMD",
    "APNA",
    "APO",
    "APOG",
    "APOS",
    "APP",
    "APPF",
    "APPN",
    "APPS",
    "APRE",
    "APSI",
    "APT",
    "APTN",
    "APTV",
    "APUR",
    "APUS",
    "APVO",
    "APWC",
    "APXT",
    "APYX",
    "AQB",
    "AQMS",
    "AQN",
    "AQNB",
    "AQST",
    "AR",
    "ARAI",
    "ARAY",
    "ARBB",
    "ARBE",
    "ARBK",
    "ARCB",
    "ARCC",
    "ARCI",
    "ARCL",
    "ARCO",
    "ARCT",
    "ARDC",
    "ARDT",
    "ARDX",
    "ARE",
    "AREB",
    "AREC",
    "AREN",
    "ARES",
    "ARGX",
    "ARHS",
    "ARI",
    "ARIS",
    "ARKB",
    "ARKO",
    "ARKR",
    "ARL",
    "ARLO",
    "ARLP",
    "ARM",
    "ARMK",
    "ARMP",
    "AROC",
    "AROW",
    "ARQ",
    "ARQQ",
    "ARQT",
    "ARR",
    "ARRT",
    "ARRY",
    "ARTC",
    "ARTL",
    "ARTV",
    "ARTW",
    "ARVN",
    "ARW",
    "ARWR",
    "ARX",
    "ARXS",
    "AS",
    "ASA",
    "ASAN",
    "ASB",
    "ASBA",
    "ASBP",
    "ASC",
    "ASFH",
    "ASFT",
    "ASG",
    "ASGI",
    "ASH",
    "ASIC",
    "ASII",
    "ASIX",
    "ASLE",
    "ASM",
    "ASMB",
    "ASML",
    "ASND",
    "ASNS",
    "ASO",
    "ASPC",
    "ASPI",
    "ASPN",
    "ASPS",
    "ASR",
    "ASRV",
    "ASST",
    "ASTC",
    "ASTE",
    "ASTH",
    "ASTI",
    "ASTL",
    "ASTS",
    "ASUR",
    "ASX",
    "ASYS",
    "ATAC",
    "ATAI",
    "ATAT",
    "ATCH",
    "ATCX",
    "ATDS",
    "ATEC",
    "ATEK",
    "ATEN",
    "ATER",
    "ATEX",
    "ATGL",
    "ATHE",
    "ATHM",
    "ATHR",
    "ATHS",
    "ATI",
    "ATII",
    "ATKR",
    "ATLC",
    "ATLO",
    "ATLX",
    "ATMH",
    "ATMP",
    "ATMU",
    "ATNI",
    "ATNM",
    "ATO",
    "ATOM",
    "ATOS",
    "ATPC",
    "ATR",
    "ATRA",
    "ATRC",
    "ATRO",
    "ATS",
    "ATTO",
    "ATVK",
    "ATXG",
    "ATXI",
    "ATYR",
    "AU",
    "AUB",
    "AUBN",
    "AUC",
    "AUDC",
    "AUGO",
    "AUID",
    "AUMN",
    "AUNA",
    "AUPH",
    "AUR",
    "AURA",
    "AURE",
    "AURX",
    "AUSI",
    "AUST",
    "AUTL",
    "AUUD",
    "AVA",
    "AVAC",
    "AVAH",
    "AVAI",
    "AVAL",
    "AVAT",
    "AVAV",
    "AVB",
    "AVBC",
    "AVBH",
    "AVBP",
    "AVD",
    "AVEX",
    "AVGO",
    "AVIR",
    "AVK",
    "AVLN",
    "AVNI",
    "AVNT",
    "AVNW",
    "AVO",
    "AVPT",
    "AVR",
    "AVT",
    "AVTR",
    "AVTX",
    "AVX",
    "AVXL",
    "AVY",
    "AWCA",
    "AWF",
    "AWHL",
    "AWI",
    "AWK",
    "AWP",
    "AWR",
    "AWRE",
    "AWX",
    "AX",
    "AXG",
    "AXGN",
    "AXIA",
    "AXIL",
    "AXIM",
    "AXIN",
    "AXON",
    "AXP",
    "AXR",
    "AXS",
    "AXSM",
    "AXTA",
    "AXTI",
    "AYA",
    "AYI",
    "AYR",
    "AYTU",
    "AZ",
    "AZI",
    "AZIO",
    "AZN",
    "AZO",
    "AZTA",
    "AZTR",
    "AZUL",
    "AZZ",
    "B",
    "BA",
    "BABA",
    "BABB",
    "BAC",
    "BACC",
    "BAER",
    "BAFN",
    "BAGZ",
    "BAH",
    "BAK",
    "BAKR",
    "BALL",
    "BALY",
    "BAM",
    "BANC",
    "BAND",
    "BANF",
    "BANL",
    "BANR",
    "BANX",
    "BAOS",
    "BAP",
    "BAR",
    "BARK",
    "BASA",
    "BATL",
    "BAVA",
    "BAX",
    "BB",
    "BBAI",
    "BBAR",
    "BBBY",
    "BBCP",
    "BBCQ",
    "BBD",
    "BBDC",
    "BBDO",
    "BBGI",
    "BBIO",
    "BBLG",
    "BBLR",
    "BBN",
    "BBNX",
    "BBOT",
    "BBSI",
    "BBT",
    "BBUC",
    "BBVA",
    "BBW",
    "BBWI",
    "BBY",
    "BC",
    "BCAB",
    "BCAL",
    "BCAR",
    "BCAT",
    "BCAX",
    "BCBP",
    "BCC",
    "BCCG",
    "BCCQ",
    "BCDA",
    "BCE",
    "BCG",
    "BCH",
    "BCHG",
    "BCHT",
    "BCIC",
    "BCLI",
    "BCML",
    "BCO",
    "BCOW",
    "BCPC",
    "BCRD",
    "BCRX",
    "BCS",
    "BCSF",
    "BCSS",
    "BCTF",
    "BCTX",
    "BCV",
    "BCX",
    "BCYC",
    "BDC",
    "BDCI",
    "BDCO",
    "BDCX",
    "BDCZ",
    "BDDD",
    "BDJ",
    "BDL",
    "BDMD",
    "BDN",
    "BDPT",
    "BDRX",
    "BDRY",
    "BDSX",
    "BDTB",
    "BDTX",
    "BDX",
    "BE",
    "BEAG",
    "BEAM",
    "BEAT",
    "BEBE",
    "BEEM",
    "BEEP",
    "BEKE",
    "BEN",
    "BENF",
    "BEOB",
    "BEP",
    "BEPC",
    "BEPH",
    "BEPI",
    "BEPJ",
    "BERZ",
    "BESS",
    "BETA",
    "BETR",
    "BFAM",
    "BFC",
    "BFCH",
    "BFH",
    "BFLY",
    "BFNH",
    "BFRG",
    "BFRI",
    "BFS",
    "BFST",
    "BG",
    "BGB",
    "BGC",
    "BGDE",
    "BGFR",
    "BGH",
    "BGI",
    "BGIN",
    "BGL",
    "BGLC",
    "BGM",
    "BGMS",
    "BGR",
    "BGS",
    "BGSF",
    "BGSI",
    "BGT",
    "BGX",
    "BGY",
    "BH",
    "BHAV",
    "BHB",
    "BHC",
    "BHE",
    "BHF",
    "BHIC",
    "BHK",
    "BHLL",
    "BHM",
    "BHP",
    "BHR",
    "BHRB",
    "BHST",
    "BHV",
    "BHVN",
    "BHYP",
    "BIAF",
    "BICX",
    "BID",
    "BIDU",
    "BIIB",
    "BIII",
    "BILI",
    "BILL",
    "BINI",
    "BIO",
    "BIOA",
    "BIOE",
    "BIOF",
    "BIOM",
    "BIOT",
    "BIOX",
    "BIP",
    "BIPC",
    "BIPH",
    "BIPI",
    "BIPJ",
    "BIRD",
    "BIRK",
    "BIT",
    "BITA",
    "BITB",
    "BITW",
    "BIVI",
    "BIXI",
    "BIXT",
    "BIYA",
    "BJ",
    "BJDX",
    "BJRI",
    "BKD",
    "BKE",
    "BKH",
    "BKHA",
    "BKKT",
    "BKNG",
    "BKPA",
    "BKR",
    "BKSY",
    "BKT",
    "BKTH",
    "BKTI",
    "BKU",
    "BKV",
    "BKYI",
    "BL",
    "BLBD",
    "BLCO",
    "BLDC",
    "BLDP",
    "BLDR",
    "BLFS",
    "BLGO",
    "BLIN",
    "BLIS",
    "BLIV",
    "BLK",
    "BLKB",
    "BLLN",
    "BLMH",
    "BLMN",
    "BLNC",
    "BLND",
    "BLNE",
    "BLNH",
    "BLNK",
    "BLPG",
    "BLRK",
    "BLRX",
    "BLSH",
    "BLSM",
    "BLTE",
    "BLTG",
    "BLTH",
    "BLUW",
    "BLW",
    "BLX",
    "BLZE",
    "BLZR",
    "BMA",
    "BMBL",
    "BMBN",
    "BME",
    "BMEA",
    "BMEZ",
    "BMGL",
    "BMHL",
    "BMI",
    "BMM",
    "BMN",
    "BMNM",
    "BMNP",
    "BMNR",
    "BMO",
    "BMOK",
    "BMPA",
    "BMR",
    "BMRA",
    "BMRC",
    "BMRN",
    "BMTM",
    "BMXI",
    "BMY",
    "BN",
    "BNAI",
    "BNBX",
    "BNC",
    "BNED",
    "BNET",
    "BNGO",
    "BNH",
    "BNJ",
    "BNKD",
    "BNKK",
    "BNKU",
    "BNL",
    "BNO",
    "BNR",
    "BNRG",
    "BNS",
    "BNT",
    "BNTC",
    "BNTX",
    "BNY",
    "BNZI",
    "BOBS",
    "BOC",
    "BODI",
    "BOE",
    "BOF",
    "BOH",
    "BOIL",
    "BOKF",
    "BOLD",
    "BOLT",
    "BON",
    "BOOM",
    "BOOT",
    "BORR",
    "BOSC",
    "BOT",
    "BOTJ",
    "BOTX",
    "BOTY",
    "BOW",
    "BOX",
    "BOXL",
    "BP",
    "BPAC",
    "BPOP",
    "BPRE",
    "BPRN",
    "BPTH",
    "BQ",
    "BQST",
    "BR",
    "BRAG",
    "BRAI",
    "BRBI",
    "BRBR",
    "BRBS",
    "BRC",
    "BRCB",
    "BRCC",
    "BREZ",
    "BRFH",
    "BRGX",
    "BRIA",
    "BRID",
    "BRKH",
    "BRKR",
    "BRLL",
    "BRLS",
    "BRLT",
    "BRN",
    "BRNS",
    "BRO",
    "BROS",
    "BRQL",
    "BRR",
    "BRRN",
    "BRRR",
    "BRSL",
    "BRSP",
    "BRT",
    "BRTM",
    "BRTX",
    "BRUN",
    "BRVE",
    "BRVO",
    "BRW",
    "BRWC",
    "BRX",
    "BRZE",
    "BSAA",
    "BSAC",
    "BSAI",
    "BSBK",
    "BSBR",
    "BSCL",
    "BSEM",
    "BSET",
    "BSFC",
    "BSIN",
    "BSL",
    "BSM",
    "BSOL",
    "BSP",
    "BSPA",
    "BSPK",
    "BSRR",
    "BST",
    "BSTR",
    "BSTT",
    "BSTZ",
    "BSVN",
    "BSX",
    "BSY",
    "BTAI",
    "BTBD",
    "BTBT",
    "BTC",
    "BTCK",
    "BTCO",
    "BTCS",
    "BTCT",
    "BTCW",
    "BTCY",
    "BTDR",
    "BTE",
    "BTG",
    "BTGO",
    "BTI",
    "BTMD",
    "BTO",
    "BTOC",
    "BTOG",
    "BTQ",
    "BTSG",
    "BTT",
    "BTTC",
    "BTU",
    "BTX",
    "BTZ",
    "BUD",
    "BUDA",
    "BUDZ",
    "BUI",
    "BUKS",
    "BULL",
    "BULZ",
    "BUR",
    "BURL",
    "BURU",
    "BUSE",
    "BUUU",
    "BV",
    "BVC",
    "BVFL",
    "BVN",
    "BVS",
    "BW",
    "BWA",
    "BWAY",
    "BWB",
    "BWEN",
    "BWET",
    "BWFG",
    "BWG",
    "BWIN",
    "BWIV",
    "BWLP",
    "BWMG",
    "BWMN",
    "BWMX",
    "BWNB",
    "BWOW",
    "BWXT",
    "BX",
    "BXBL",
    "BXC",
    "BXDC",
    "BXMT",
    "BXP",
    "BXSL",
    "BXSY",
    "BY",
    "BYAH",
    "BYD",
    "BYFC",
    "BYND",
    "BYNO",
    "BYRN",
    "BYSI",
    "BZ",
    "BZAI",
    "BZFD",
    "BZH",
    "BZUN",
    "BZYR",
    "C",
    "CAAP",
    "CAAS",
    "CABA",
    "CABO",
    "CABR",
    "CAC",
    "CACC",
    "CACI",
    "CADL",
    "CAE",
    "CAES",
    "CAF",
    "CAG",
    "CAH",
    "CAHO",
    "CAI",
    "CAII",
    "CAKE",
    "CAL",
    "CALC",
    "CALM",
    "CALX",
    "CALY",
    "CAMP",
    "CAMT",
    "CAN",
    "CANE",
    "CANF",
    "CANG",
    "CANN",
    "CAPC",
    "CAPI",
    "CAPL",
    "CAPN",
    "CAPR",
    "CAPS",
    "CAQ",
    "CAR",
    "CARD",
    "CARE",
    "CARG",
    "CARL",
    "CARR",
    "CARS",
    "CART",
    "CARU",
    "CARV",
    "CASH",
    "CASS",
    "CAST",
    "CASY",
    "CAT",
    "CATL",
    "CATO",
    "CATX",
    "CATY",
    "CAVA",
    "CB",
    "CBAI",
    "CBAN",
    "CBAT",
    "CBC",
    "CBDL",
    "CBDW",
    "CBDY",
    "CBFV",
    "CBIH",
    "CBIO",
    "CBK",
    "CBKM",
    "CBL",
    "CBLL",
    "CBLO",
    "CBMJ",
    "CBNA",
    "CBNK",
    "CBOE",
    "CBRE",
    "CBRL",
    "CBRS",
    "CBSH",
    "CBT",
    "CBU",
    "CBUS",
    "CBZ",
    "CC",
    "CCAP",
    "CCAQ",
    "CCB",
    "CCBG",
    "CCC",
    "CCCC",
    "CCCT",
    "CCD",
    "CCEC",
    "CCEL",
    "CCEP",
    "CCFN",
    "CCG",
    "CCHH",
    "CCI",
    "CCID",
    "CCIF",
    "CCII",
    "CCIL",
    "CCJ",
    "CCK",
    "CCL",
    "CCLD",
    "CCLV",
    "CCM",
    "CCNB",
    "CCNE",
    "CCO",
    "CCOI",
    "CCS",
    "CCSI",
    "CCTG",
    "CCU",
    "CCXI",
    "CCZ",
    "CD",
    "CDE",
    "CDIO",
    "CDIX",
    "CDLR",
    "CDLX",
    "CDNA",
    "CDNL",
    "CDNS",
    "CDP",
    "CDRE",
    "CDRO",
    "CDSG",
    "CDT",
    "CDTG",
    "CDW",
    "CDXS",
    "CDZI",
    "CE",
    "CECO",
    "CEE",
    "CEF",
    "CEFD",
    "CEG",
    "CEIN",
    "CELC",
    "CELH",
    "CELU",
    "CELZ",
    "CENN",
    "CENT",
    "CENX",
    "CEPF",
    "CEPL",
    "CEPO",
    "CEPS",
    "CEPU",
    "CEPV",
    "CERO",
    "CERS",
    "CERT",
    "CET",
    "CETI",
    "CETX",
    "CETY",
    "CEV",
    "CEVA",
    "CF",
    "CFBK",
    "CFFI",
    "CFFN",
    "CFG",
    "CFNB",
    "CFND",
    "CFOO",
    "CFOR",
    "CFR",
    "CFSU",
    "CG",
    "CGAU",
    "CGBD",
    "CGC",
    "CGCF",
    "CGEM",
    "CGEN",
    "CGNT",
    "CGNX",
    "CGO",
    "CGON",
    "CGTL",
    "CGTX",
    "CHA",
    "CHAI",
    "CHAR",
    "CHCI",
    "CHCO",
    "CHCT",
    "CHD",
    "CHDN",
    "CHE",
    "CHEC",
    "CHEF",
    "CHEV",
    "CHGA",
    "CHGG",
    "CHH",
    "CHI",
    "CHKP",
    "CHKR",
    "CHMG",
    "CHMI",
    "CHNR",
    "CHON",
    "CHOW",
    "CHPG",
    "CHPT",
    "CHR",
    "CHRD",
    "CHRN",
    "CHRS",
    "CHRW",
    "CHSN",
    "CHT",
    "CHTR",
    "CHUC",
    "CHW",
    "CHWM",
    "CHWY",
    "CHY",
    "CHYM",
    "CI",
    "CIA",
    "CIB",
    "CICB",
    "CICC",
    "CIEN",
    "CIFR",
    "CIG",
    "CIGI",
    "CIGL",
    "CII",
    "CIIT",
    "CIK",
    "CIM",
    "CIMG",
    "CIMN",
    "CIMO",
    "CIMP",
    "CINF",
    "CING",
    "CINT",
    "CION",
    "CIRC",
    "CIRX",
    "CISO",
    "CISS",
    "CITR",
    "CIVB",
    "CIX",
    "CIZN",
    "CJAX",
    "CJMB",
    "CKX",
    "CL",
    "CLAR",
    "CLB",
    "CLBK",
    "CLBR",
    "CLBT",
    "CLBZ",
    "CLCS",
    "CLDI",
    "CLDT",
    "CLDX",
    "CLEV",
    "CLF",
    "CLFD",
    "CLGN",
    "CLH",
    "CLIK",
    "CLIR",
    "CLLS",
    "CLM",
    "CLMB",
    "CLMT",
    "CLNE",
    "CLNK",
    "CLNN",
    "CLNV",
    "CLOQ",
    "CLOV",
    "CLOW",
    "CLPR",
    "CLPS",
    "CLPT",
    "CLRB",
    "CLRI",
    "CLRO",
    "CLS",
    "CLSK",
    "CLST",
    "CLUS",
    "CLVT",
    "CLW",
    "CLWT",
    "CLX",
    "CLYD",
    "CLYM",
    "CM",
    "CMBT",
    "CMBY",
    "CMC",
    "CMCL",
    "CMCM",
    "CMCO",
    "CMCT",
    "CMDB",
    "CME",
    "CMG",
    "CMI",
    "CMII",
    "CMLS",
    "CMMB",
    "CMND",
    "CMP",
    "CMPR",
    "CMPS",
    "CMPX",
    "CMRC",
    "CMRE",
    "CMRF",
    "CMS",
    "CMSA",
    "CMSC",
    "CMSD",
    "CMT",
    "CMTG",
    "CMTL",
    "CMTV",
    "CNA",
    "CNBX",
    "CNC",
    "CNCK",
    "CNDA",
    "CNDT",
    "CNET",
    "CNEY",
    "CNF",
    "CNFN",
    "CNH",
    "CNI",
    "CNK",
    "CNL",
    "CNM",
    "CNMD",
    "CNNE",
    "CNO",
    "CNOB",
    "CNP",
    "CNQ",
    "CNR",
    "CNS",
    "CNSP",
    "CNSY",
    "CNTB",
    "CNTM",
    "CNTN",
    "CNTX",
    "CNTY",
    "CNVS",
    "CNX",
    "CNXC",
    "CNXN",
    "CNXU",
    "COAG",
    "COBA",
    "COCH",
    "COCO",
    "COCP",
    "CODA",
    "CODI",
    "CODX",
    "COE",
    "COF",
    "COFS",
    "COGT",
    "COHN",
    "COHR",
    "COHU",
    "COIN",
    "COKE",
    "COLA",
    "COLB",
    "COLD",
    "COLL",
    "COLM",
    "COMP",
    "CON",
    "CONC",
    "CONE",
    "COO",
    "COOK",
    "COOT",
    "COP",
    "COPL",
    "COPR",
    "COR",
    "CORN",
    "CORT",
    "CORZ",
    "COSG",
    "COSM",
    "COSO",
    "COST",
    "COTY",
    "COUR",
    "COYA",
    "CP",
    "CPA",
    "CPAC",
    "CPAY",
    "CPB",
    "CPBI",
    "CPER",
    "CPF",
    "CPHC",
    "CPHI",
    "CPIX",
    "CPK",
    "CPKF",
    "CPLX",
    "CPMD",
    "CPMV",
    "CPNG",
    "CPOP",
    "CPRI",
    "CPRT",
    "CPS",
    "CPSH",
    "CPSS",
    "CPT",
    "CPTP",
    "CPWR",
    "CPZ",
    "CQP",
    "CR",
    "CRAC",
    "CRAI",
    "CRAN",
    "CRAQ",
    "CRBD",
    "CRBG",
    "CRBP",
    "CRBU",
    "CRC",
    "CRCE",
    "CRCL",
    "CRCT",
    "CRCW",
    "CRDF",
    "CRDL",
    "CRDO",
    "CRDV",
    "CRE",
    "CREG",
    "CREX",
    "CRF",
    "CRGO",
    "CRGT",
    "CRGY",
    "CRH",
    "CRI",
    "CRIS",
    "CRK",
    "CRL",
    "CRM",
    "CRMD",
    "CRML",
    "CRMT",
    "CRMZ",
    "CRNC",
    "CRNT",
    "CRNX",
    "CRON",
    "CROX",
    "CRS",
    "CRSF",
    "CRSP",
    "CRSR",
    "CRT",
    "CRTD",
    "CRTO",
    "CRUS",
    "CRVL",
    "CRVO",
    "CRVS",
    "CRVW",
    "CRWD",
    "CRWE",
    "CRWS",
    "CRWV",
    "CSAI",
    "CSAN",
    "CSBA",
    "CSBB",
    "CSBR",
    "CSCM",
    "CSCO",
    "CSDX",
    "CSGP",
    "CSHR",
    "CSIQ",
    "CSL",
    "CSPI",
    "CSQ",
    "CSQR",
    "CSR",
    "CSTE",
    "CSTL",
    "CSTM",
    "CSUI",
    "CSV",
    "CSW",
    "CSWC",
    "CSX",
    "CTAA",
    "CTAS",
    "CTBI",
    "CTEV",
    "CTGG",
    "CTGL",
    "CTGO",
    "CTHH",
    "CTKB",
    "CTM",
    "CTMX",
    "CTNM",
    "CTNT",
    "CTO",
    "CTOR",
    "CTOS",
    "CTRE",
    "CTRI",
    "CTRM",
    "CTRN",
    "CTS",
    "CTSH",
    "CTSO",
    "CTTH",
    "CTVA",
    "CTW",
    "CTWO",
    "CTXR",
    "CUB",
    "CUBB",
    "CUBE",
    "CUBI",
    "CUBT",
    "CUE",
    "CUEN",
    "CULL",
    "CULP",
    "CUPR",
    "CURB",
    "CURI",
    "CURR",
    "CURV",
    "CURX",
    "CUVL",
    "CUZ",
    "CV",
    "CVAT",
    "CVBF",
    "CVCO",
    "CVE",
    "CVEO",
    "CVGI",
    "CVI",
    "CVKD",
    "CVLG",
    "CVLT",
    "CVM",
    "CVNA",
    "CVR",
    "CVRX",
    "CVS",
    "CVSA",
    "CVSI",
    "CVU",
    "CVV",
    "CVX",
    "CW",
    "CWBC",
    "CWCO",
    "CWD",
    "CWEN",
    "CWGL",
    "CWH",
    "CWK",
    "CWPE",
    "CWST",
    "CWT",
    "CX",
    "CXAI",
    "CXDO",
    "CXII",
    "CXM",
    "CXT",
    "CXW",
    "CYAB",
    "CYAN",
    "CYCN",
    "CYCU",
    "CYD",
    "CYDX",
    "CYDY",
    "CYH",
    "CYN",
    "CYPH",
    "CYRX",
    "CYTK",
    "CZFS",
    "CZNC",
    "CZR",
    "CZWI",
    "D",
    "DAAQ",
    "DAC",
    "DAIC",
    "DAIO",
    "DAKT",
    "DAL",
    "DAN",
    "DAO",
    "DAR",
    "DARE",
    "DASH",
    "DAVA",
    "DAVE",
    "DAVI",
    "DB",
    "DBA",
    "DBB",
    "DBC",
    "DBCA",
    "DBD",
    "DBE",
    "DBGI",
    "DBHL",
    "DBI",
    "DBL",
    "DBMM",
    "DBO",
    "DBP",
    "DBRG",
    "DBVT",
    "DBX",
    "DC",
    "DCBG",
    "DCBO",
    "DCGO",
    "DCH",
    "DCI",
    "DCO",
    "DCOM",
    "DCOY",
    "DCTH",
    "DCX",
    "DD",
    "DDC",
    "DDD",
    "DDDX",
    "DDI",
    "DDL",
    "DDOG",
    "DDS",
    "DDT",
    "DE",
    "DEA",
    "DEC",
    "DECK",
    "DEFG",
    "DEFI",
    "DEFT",
    "DEI",
    "DELL",
    "DEO",
    "DERM",
    "DETX",
    "DFDV",
    "DFH",
    "DFIN",
    "DFLI",
    "DFNS",
    "DFP",
    "DFPH",
    "DFSC",
    "DFTX",
    "DG",
    "DGAC",
    "DGII",
    "DGNX",
    "DGP",
    "DGX",
    "DGXX",
    "DGZ",
    "DH",
    "DHC",
    "DHF",
    "DHGR",
    "DHI",
    "DHR",
    "DHT",
    "DHTI",
    "DHX",
    "DHY",
    "DIA",
    "DIBS",
    "DIN",
    "DINO",
    "DIOD",
    "DIS",
    "DIT",
    "DJCO",
    "DJP",
    "DJT",
    "DK",
    "DKI",
    "DKL",
    "DKNG",
    "DKS",
    "DLB",
    "DLHC",
    "DLNG",
    "DLO",
    "DLPN",
    "DLR",
    "DLTH",
    "DLTI",
    "DLTR",
    "DLX",
    "DLXY",
    "DLY",
    "DMA",
    "DMAA",
    "DMAC",
    "DMB",
    "DMC",
    "DMII",
    "DMLP",
    "DMO",
    "DMRA",
    "DMRC",
    "DNA",
    "DNKC",
    "DNLI",
    "DNMX",
    "DNN",
    "DNOW",
    "DNP",
    "DNTH",
    "DNUT",
    "DOC",
    "DOCN",
    "DOCS",
    "DOCU",
    "DOGP",
    "DOGZ",
    "DOLE",
    "DOMH",
    "DOMO",
    "DOO",
    "DORM",
    "DOUG",
    "DOV",
    "DOW",
    "DOX",
    "DOYU",
    "DPC",
    "DPG",
    "DPLS",
    "DPRO",
    "DPU",
    "DPUI",
    "DPZ",
    "DQ",
    "DQWS",
    "DRCT",
    "DRD",
    "DRDB",
    "DREM",
    "DRH",
    "DRI",
    "DRIO",
    "DRMA",
    "DROR",
    "DRS",
    "DRTS",
    "DRUG",
    "DRVN",
    "DSAC",
    "DSC",
    "DSGN",
    "DSGR",
    "DSGT",
    "DSGX",
    "DSL",
    "DSM",
    "DSNY",
    "DSP",
    "DSS",
    "DSU",
    "DSWL",
    "DSX",
    "DSY",
    "DT",
    "DTB",
    "DTCX",
    "DTE",
    "DTF",
    "DTG",
    "DTGI",
    "DTI",
    "DTII",
    "DTIL",
    "DTK",
    "DTM",
    "DTSQ",
    "DTSS",
    "DTST",
    "DTW",
    "DUK",
    "DUKB",
    "DUKR",
    "DULL",
    "DUO",
    "DUOL",
    "DUOT",
    "DV",
    "DVA",
    "DVLT",
    "DVN",
    "DWAY",
    "DWNX",
    "DWSN",
    "DWTX",
    "DX",
    "DXC",
    "DXCM",
    "DXF",
    "DXLG",
    "DXPE",
    "DXR",
    "DXST",
    "DXYN",
    "DXYZ",
    "DY",
    "DYAI",
    "DYN",
    "DYNC",
    "DYNR",
    "DYOR",
    "DZZ",
    "E",
    "EA",
    "EACO",
    "EAD",
    "EAF",
    "EAI",
    "EARI",
    "EARN",
    "EAT",
    "EAXR",
    "EBAY",
    "EBC",
    "EBF",
    "EBMT",
    "EBON",
    "EBS",
    "EBZT",
    "EC",
    "ECAT",
    "ECBK",
    "ECC",
    "ECCC",
    "ECCU",
    "ECCV",
    "ECF",
    "ECG",
    "ECHO",
    "ECIA",
    "ECL",
    "ECO",
    "ECOR",
    "ECPG",
    "ECPL",
    "ECTM",
    "ECVT",
    "ECX",
    "ECXJ",
    "ED",
    "EDBL",
    "EDD",
    "EDF",
    "EDGM",
    "EDHL",
    "EDIT",
    "EDN",
    "EDRY",
    "EDSA",
    "EDTK",
    "EDU",
    "EDUC",
    "EDVR",
    "EE",
    "EEA",
    "EEFT",
    "EEGI",
    "EEIQ",
    "EESH",
    "EFC",
    "EFGH",
    "EFOI",
    "EFOR",
    "EFR",
    "EFSC",
    "EFSI",
    "EFT",
    "EFTY",
    "EFX",
    "EFXT",
    "EG",
    "EGAN",
    "EGBN",
    "EGG",
    "EGHA",
    "EGHT",
    "EGO",
    "EGP",
    "EGY",
    "EH",
    "EHC",
    "EHGO",
    "EHI",
    "EHLD",
    "EHSI",
    "EHTH",
    "EIC",
    "EICA",
    "EIG",
    "EIIA",
    "EIKN",
    "EIM",
    "EIX",
    "EJH",
    "EL",
    "ELA",
    "ELAB",
    "ELAN",
    "ELBM",
    "ELC",
    "ELDN",
    "ELE",
    "ELF",
    "ELLA",
    "ELLO",
    "ELMD",
    "ELME",
    "ELMT",
    "ELOG",
    "ELOX",
    "ELPC",
    "ELPW",
    "ELRE",
    "ELS",
    "ELSE",
    "ELTK",
    "ELTP",
    "ELTX",
    "ELUT",
    "ELV",
    "ELVA",
    "ELVG",
    "ELVN",
    "ELVR",
    "ELWT",
    "EMA",
    "EMAT",
    "EMBC",
    "EMBJ",
    "EMD",
    "EME",
    "EMED",
    "EMF",
    "EMI",
    "EMIS",
    "EML",
    "EMMA",
    "EMN",
    "EMO",
    "EMP",
    "EMPD",
    "EMR",
    "EMRH",
    "EMYB",
    "ENB",
    "ENBP",
    "ENDI",
    "ENDV",
    "ENGN",
    "ENGS",
    "ENHA",
    "ENIC",
    "ENJ",
    "ENLT",
    "ENLV",
    "ENO",
    "ENOV",
    "ENPH",
    "ENR",
    "ENRD",
    "ENRT",
    "ENS",
    "ENSC",
    "ENSG",
    "ENT",
    "ENTA",
    "ENTG",
    "ENTX",
    "ENVA",
    "ENVB",
    "ENVX",
    "ENZN",
    "EOD",
    "EOG",
    "EOI",
    "EOLS",
    "EONR",
    "EOS",
    "EOSE",
    "EOT",
    "EP",
    "EPAC",
    "EPAM",
    "EPC",
    "EPD",
    "EPDU",
    "EPM",
    "EPOW",
    "EPR",
    "EPRT",
    "EPRX",
    "EPSM",
    "EPSN",
    "EQ",
    "EQBK",
    "EQH",
    "EQIX",
    "EQNR",
    "EQPT",
    "EQR",
    "EQS",
    "EQT",
    "EQX",
    "ERAS",
    "ERC",
    "ERH",
    "ERIC",
    "ERIE",
    "ERII",
    "ERNA",
    "ERO",
    "EROC",
    "EROK",
    "ES",
    "ESAB",
    "ESBA",
    "ESCA",
    "ESE",
    "ESEA",
    "ESGH",
    "ESI",
    "ESLA",
    "ESLT",
    "ESMC",
    "ESMR",
    "ESNT",
    "ESOA",
    "ESP",
    "ESQ",
    "ESRT",
    "ESS",
    "ESSI",
    "ESTA",
    "ESTC",
    "ET",
    "ETB",
    "ETCG",
    "ETD",
    "ETG",
    "ETH",
    "ETHA",
    "ETHB",
    "ETHE",
    "ETHV",
    "ETHW",
    "ETJ",
    "ETN",
    "ETO",
    "ETON",
    "ETOR",
    "ETR",
    "ETS",
    "ETSS",
    "ETST",
    "ETSY",
    "ETV",
    "ETW",
    "ETX",
    "ETY",
    "EU",
    "EUBG",
    "EUDA",
    "EUO",
    "EURK",
    "EVAC",
    "EVAX",
    "EVC",
    "EVCM",
    "EVER",
    "EVEX",
    "EVF",
    "EVFM",
    "EVG",
    "EVGN",
    "EVGO",
    "EVH",
    "EVI",
    "EVLV",
    "EVMN",
    "EVN",
    "EVO",
    "EVOH",
    "EVON",
    "EVOX",
    "EVR",
    "EVRG",
    "EVT",
    "EVTC",
    "EVTK",
    "EVTL",
    "EVV",
    "EW",
    "EWAV",
    "EWBC",
    "EWSB",
    "EWTX",
    "EXC",
    "EXE",
    "EXEL",
    "EXFY",
    "EXG",
    "EXK",
    "EXLS",
    "EXOD",
    "EXOZ",
    "EXP",
    "EXPD",
    "EXPE",
    "EXPO",
    "EXR",
    "EXTR",
    "EXYN",
    "EYE",
    "EYPT",
    "EZBC",
    "EZET",
    "EZGO",
    "EZPW",
    "EZPZ",
    "EZRA",
    "F",
    "FA",
    "FABC",
    "FAC",
    "FACT",
    "FAF",
    "FAMI",
    "FANG",
    "FAST",
    "FATE",
    "FATN",
    "FAX",
    "FBCD",
    "FBDT",
    "FBGL",
    "FBIN",
    "FBIO",
    "FBIZ",
    "FBK",
    "FBLA",
    "FBLG",
    "FBNC",
    "FBP",
    "FBRT",
    "FBRX",
    "FBSI",
    "FBTC",
    "FBYD",
    "FC",
    "FCAP",
    "FCBC",
    "FCBM",
    "FCCI",
    "FCCN",
    "FCCO",
    "FCEL",
    "FCF",
    "FCFS",
    "FCHL",
    "FCHS",
    "FCN",
    "FCPT",
    "FCRS",
    "FCT",
    "FCUV",
    "FCX",
    "FDBC",
    "FDCT",
    "FDMM",
    "FDMT",
    "FDS",
    "FDSB",
    "FDUS",
    "FDX",
    "FDXF",
    "FE",
    "FEAM",
    "FEAV",
    "FEBO",
    "FEDU",
    "FEED",
    "FEIM",
    "FELE",
    "FEMY",
    "FENC",
    "FENG",
    "FER",
    "FERA",
    "FERG",
    "FET",
    "FETH",
    "FF",
    "FFA",
    "FFAI",
    "FFBC",
    "FFC",
    "FFGG",
    "FFIN",
    "FFIV",
    "FFLO",
    "FG",
    "FGBI",
    "FGCO",
    "FGDL",
    "FGFH",
    "FGI",
    "FGII",
    "FGL",
    "FGN",
    "FGNX",
    "FGPR",
    "FGRS",
    "FGSN",
    "FHB",
    "FHI",
    "FHN",
    "FHTX",
    "FIBK",
    "FICO",
    "FIEE",
    "FIG",
    "FIGP",
    "FIGR",
    "FIGS",
    "FIGX",
    "FILG",
    "FINS",
    "FINV",
    "FINW",
    "FIP",
    "FIRY",
    "FIS",
    "FISI",
    "FISK",
    "FISN",
    "FISV",
    "FITB",
    "FITY",
    "FIVE",
    "FIVN",
    "FIX",
    "FIZZ",
    "FJET",
    "FKWL",
    "FKYS",
    "FLC",
    "FLD",
    "FLEX",
    "FLG",
    "FLGT",
    "FLL",
    "FLNA",
    "FLNC",
    "FLNG",
    "FLNT",
    "FLO",
    "FLOC",
    "FLR",
    "FLS",
    "FLUT",
    "FLUX",
    "FLWS",
    "FLX",
    "FLXS",
    "FLY",
    "FLYD",
    "FLYE",
    "FLYU",
    "FLYW",
    "FLYX",
    "FLZH",
    "FMAC",
    "FMAO",
    "FMBH",
    "FMBM",
    "FMC",
    "FMCB",
    "FMCC",
    "FMFC",
    "FMFG",
    "FMHS",
    "FMN",
    "FMNB",
    "FMS",
    "FMST",
    "FMX",
    "FMY",
    "FN",
    "FNB",
    "FND",
    "FNF",
    "FNFI",
    "FNGD",
    "FNGO",
    "FNGR",
    "FNGS",
    "FNGU",
    "FNKO",
    "FNLC",
    "FNMA",
    "FNRN",
    "FNUC",
    "FNV",
    "FNWB",
    "FNWD",
    "FOA",
    "FOCL",
    "FOF",
    "FOFA",
    "FOFO",
    "FOIL",
    "FOR",
    "FORM",
    "FORR",
    "FOSL",
    "FOTB",
    "FOUR",
    "FOX",
    "FOXA",
    "FOXF",
    "FOXO",
    "FOXX",
    "FPF",
    "FPH",
    "FPI",
    "FPS",
    "FR",
    "FRA",
    "FRAF",
    "FRBP",
    "FRBT",
    "FRD",
    "FRGT",
    "FRHC",
    "FRME",
    "FRMI",
    "FRMM",
    "FRNM",
    "FRO",
    "FROG",
    "FRPH",
    "FRPT",
    "FRSH",
    "FRST",
    "FRSX",
    "FRT",
    "FRTT",
    "FRVO",
    "FSBC",
    "FSBW",
    "FSCO",
    "FSEA",
    "FSHP",
    "FSI",
    "FSK",
    "FSLR",
    "FSLY",
    "FSM",
    "FSOL",
    "FSP",
    "FSS",
    "FSSL",
    "FSTJ",
    "FSTR",
    "FSUN",
    "FSV",
    "FT",
    "FTAI",
    "FTCI",
    "FTCO",
    "FTDR",
    "FTEK",
    "FTF",
    "FTFT",
    "FTH",
    "FTHA",
    "FTHM",
    "FTHY",
    "FTI",
    "FTK",
    "FTLF",
    "FTNT",
    "FTRA",
    "FTRE",
    "FTRK",
    "FTS",
    "FTV",
    "FTW",
    "FUBO",
    "FUFU",
    "FUL",
    "FULC",
    "FULO",
    "FULT",
    "FUN",
    "FUNC",
    "FUND",
    "FUNI",
    "FURY",
    "FUSB",
    "FUSE",
    "FUST",
    "FUTU",
    "FVAV",
    "FVCB",
    "FVN",
    "FVR",
    "FVRR",
    "FVTI",
    "FWAC",
    "FWDI",
    "FWFW",
    "FWRD",
    "FWRG",
    "FXA",
    "FXAC",
    "FXB",
    "FXBY",
    "FXC",
    "FXE",
    "FXF",
    "FXHO",
    "FXNC",
    "FXY",
    "FYNN",
    "FZMD",
    "G",
    "GAB",
    "GABC",
    "GAFC",
    "GAIA",
    "GAIN",
    "GALT",
    "GAM",
    "GAME",
    "GAMG",
    "GANX",
    "GAP",
    "GASS",
    "GATX",
    "GAU",
    "GAUZ",
    "GAVA",
    "GBAB",
    "GBAT",
    "GBCI",
    "GBCS",
    "GBDC",
    "GBFH",
    "GBLI",
    "GBNB",
    "GBNY",
    "GBR",
    "GBTC",
    "GBTG",
    "GBUG",
    "GBUX",
    "GBX",
    "GCAN",
    "GCBC",
    "GCDT",
    "GCGJ",
    "GCGR",
    "GCL",
    "GCMG",
    "GCO",
    "GCT",
    "GCTK",
    "GCTS",
    "GCV",
    "GD",
    "GDC",
    "GDDY",
    "GDEV",
    "GDHG",
    "GDL",
    "GDLC",
    "GDLG",
    "GDMT",
    "GDO",
    "GDOG",
    "GDOT",
    "GDRX",
    "GDS",
    "GDST",
    "GDTC",
    "GDV",
    "GDXD",
    "GDXU",
    "GDYN",
    "GE",
    "GECC",
    "GEDC",
    "GEF",
    "GEG",
    "GEHC",
    "GEL",
    "GELS",
    "GEMI",
    "GEN",
    "GENB",
    "GENC",
    "GENI",
    "GENK",
    "GENN",
    "GEO",
    "GEOS",
    "GERN",
    "GETY",
    "GEV",
    "GEVO",
    "GF",
    "GFAI",
    "GFF",
    "GFI",
    "GFL",
    "GFLT",
    "GFMH",
    "GFR",
    "GFS",
    "GFUZ",
    "GGAL",
    "GGB",
    "GGBY",
    "GGG",
    "GGN",
    "GGR",
    "GGRP",
    "GGT",
    "GGZ",
    "GH",
    "GHC",
    "GHG",
    "GHI",
    "GHM",
    "GHRS",
    "GHST",
    "GHXI",
    "GHY",
    "GIB",
    "GIBO",
    "GIC",
    "GIFT",
    "GIGM",
    "GIII",
    "GIL",
    "GILD",
    "GILT",
    "GIPL",
    "GIPR",
    "GIS",
    "GITS",
    "GIVE",
    "GIW",
    "GIX",
    "GIXI",
    "GJH",
    "GJO",
    "GJP",
    "GJR",
    "GJS",
    "GJT",
    "GKOS",
    "GL",
    "GLAD",
    "GLAI",
    "GLAS",
    "GLBE",
    "GLBS",
    "GLBZ",
    "GLD",
    "GLDG",
    "GLDI",
    "GLDM",
    "GLE",
    "GLED",
    "GLEI",
    "GLGI",
    "GLIV",
    "GLL",
    "GLMD",
    "GLND",
    "GLNG",
    "GLNK",
    "GLNS",
    "GLO",
    "GLOB",
    "GLOH",
    "GLOO",
    "GLP",
    "GLPI",
    "GLQ",
    "GLRE",
    "GLSI",
    "GLTK",
    "GLTR",
    "GLU",
    "GLUC",
    "GLUE",
    "GLV",
    "GLW",
    "GLXG",
    "GLXY",
    "GLXZ",
    "GM",
    "GMAB",
    "GMBL",
    "GME",
    "GMED",
    "GMER",
    "GMEX",
    "GMHS",
    "GMM",
    "GMRS",
    "GMTL",
    "GMZP",
    "GNE",
    "GNK",
    "GNL",
    "GNLN",
    "GNLX",
    "GNPX",
    "GNRC",
    "GNS",
    "GNSS",
    "GNT",
    "GNTA",
    "GNTX",
    "GNVR",
    "GNW",
    "GO",
    "GOAI",
    "GOF",
    "GOGO",
    "GOGR",
    "GOLD",
    "GOLF",
    "GOOD",
    "GOOG",
    "GOOS",
    "GORO",
    "GOSS",
    "GOTU",
    "GOVB",
    "GOVX",
    "GOW",
    "GP",
    "GPAC",
    "GPAT",
    "GPC",
    "GPCR",
    "GPGI",
    "GPI",
    "GPJA",
    "GPK",
    "GPLB",
    "GPLL",
    "GPMT",
    "GPN",
    "GPOR",
    "GPOX",
    "GPRE",
    "GPRK",
    "GPRO",
    "GPUS",
    "GRAB",
    "GRAL",
    "GRAN",
    "GRBK",
    "GRC",
    "GRCE",
    "GRDN",
    "GRDX",
    "GREH",
    "GRF",
    "GRFS",
    "GRHI",
    "GRI",
    "GRLF",
    "GRML",
    "GRMN",
    "GRN",
    "GRND",
    "GRNL",
    "GRNQ",
    "GRNT",
    "GRO",
    "GROV",
    "GROW",
    "GROY",
    "GRPN",
    "GRPS",
    "GRRR",
    "GRSD",
    "GRVE",
    "GRVT",
    "GRVY",
    "GRWG",
    "GRX",
    "GS",
    "GSAC",
    "GSAT",
    "GSBC",
    "GSBD",
    "GSCE",
    "GSFI",
    "GSG",
    "GSHD",
    "GSHR",
    "GSIT",
    "GSIW",
    "GSK",
    "GSL",
    "GSM",
    "GSMT",
    "GSNR",
    "GSOL",
    "GSRF",
    "GSRV",
    "GSTK",
    "GSTX",
    "GSUI",
    "GSUN",
    "GT",
    "GTAO",
    "GTBP",
    "GTCH",
    "GTE",
    "GTEC",
    "GTEN",
    "GTES",
    "GTHP",
    "GTIC",
    "GTIM",
    "GTLB",
    "GTLL",
    "GTM",
    "GTN",
    "GTX",
    "GTY",
    "GUAC",
    "GUER",
    "GUG",
    "GURE",
    "GUT",
    "GUTS",
    "GV",
    "GVA",
    "GVAC",
    "GVH",
    "GWAV",
    "GWH",
    "GWLL",
    "GWRE",
    "GWRS",
    "GWSO",
    "GWTI",
    "GWW",
    "GXAI",
    "GXLM",
    "GXO",
    "GXRP",
    "GXXM",
    "GYGY",
    "GYRE",
    "GYRO",
    "H",
    "HACQ",
    "HAE",
    "HAFC",
    "HAFG",
    "HAFN",
    "HAIN",
    "HAL",
    "HALO",
    "HAO",
    "HAPN",
    "HAS",
    "HASI",
    "HAVA",
    "HAWK",
    "HAYW",
    "HBAN",
    "HBB",
    "HBCP",
    "HBIA",
    "HBIO",
    "HBM",
    "HBNB",
    "HBNC",
    "HBT",
    "HBUV",
    "HCA",
    "HCAC",
    "HCAI",
    "HCAT",
    "HCAX",
    "HCC",
    "HCHL",
    "HCI",
    "HCIC",
    "HCIL",
    "HCKT",
    "HCM",
    "HCMA",
    "HCMC",
    "HCSG",
    "HCTI",
    "HCWB",
    "HCWC",
    "HCXY",
    "HD",
    "HDB",
    "HDL",
    "HDLB",
    "HDRN",
    "HDSN",
    "HE",
    "HEI",
    "HELE",
    "HELP",
    "HEPA",
    "HEPS",
    "HEQ",
    "HERE",
    "HERZ",
    "HESM",
    "HFBL",
    "HFFG",
    "HFRO",
    "HFUS",
    "HFWA",
    "HG",
    "HGAS",
    "HGBL",
    "HGIT",
    "HGLB",
    "HGTY",
    "HGV",
    "HGYN",
    "HHH",
    "HHS",
    "HIG",
    "HIGR",
    "HIHO",
    "HII",
    "HIMS",
    "HIMX",
    "HIND",
    "HIO",
    "HIPO",
    "HIRU",
    "HIT",
    "HITI",
    "HIVE",
    "HIW",
    "HIX",
    "HKD",
    "HKHC",
    "HKIT",
    "HKPD",
    "HL",
    "HLEO",
    "HLF",
    "HLI",
    "HLIO",
    "HLIT",
    "HLLY",
    "HLMN",
    "HLN",
    "HLNE",
    "HLP",
    "HLT",
    "HLTC",
    "HLX",
    "HLXC",
    "HLYK",
    "HMC",
    "HMH",
    "HMMR",
    "HMN",
    "HMR",
    "HMY",
    "HNGE",
    "HNI",
    "HNIT",
    "HNNA",
    "HNOI",
    "HNRG",
    "HNST",
    "HNUC",
    "HNVR",
    "HODL",
    "HODO",
    "HOFT",
    "HOG",
    "HOLO",
    "HOMB",
    "HON",
    "HONA",
    "HOOD",
    "HOPE",
    "HOUR",
    "HOV",
    "HOVR",
    "HOWL",
    "HP",
    "HPAI",
    "HPE",
    "HPF",
    "HPI",
    "HPK",
    "HPP",
    "HPQ",
    "HPS",
    "HQ",
    "HQH",
    "HQI",
    "HQL",
    "HQY",
    "HR",
    "HRB",
    "HRGN",
    "HRI",
    "HRL",
    "HRMY",
    "HROW",
    "HRTG",
    "HRTX",
    "HRZN",
    "HSAI",
    "HSBC",
    "HSCS",
    "HSCT",
    "HSDT",
    "HSHP",
    "HSIC",
    "HSLV",
    "HST",
    "HSTA",
    "HSTC",
    "HSTI",
    "HSTM",
    "HSY",
    "HTB",
    "HTCO",
    "HTCR",
    "HTD",
    "HTFC",
    "HTFL",
    "HTGC",
    "HTH",
    "HTHT",
    "HTLD",
    "HTLM",
    "HTO",
    "HTOO",
    "HTT",
    "HTZ",
    "HUBB",
    "HUBC",
    "HUBG",
    "HUBS",
    "HUDI",
    "HUHU",
    "HUIZ",
    "HUM",
    "HUMA",
    "HUN",
    "HURA",
    "HURC",
    "HURN",
    "HUT",
    "HUYA",
    "HVII",
    "HVMC",
    "HVT",
    "HWBK",
    "HWC",
    "HWH",
    "HWKE",
    "HWKN",
    "HWM",
    "HWNI",
    "HXHX",
    "HXL",
    "HY",
    "HYEX",
    "HYFM",
    "HYFT",
    "HYGD",
    "HYGU",
    "HYI",
    "HYLN",
    "HYMC",
    "HYNE",
    "HYOR",
    "HYPD",
    "HYPG",
    "HYPR",
    "HYSR",
    "HYT",
    "HZEN",
    "HZO",
    "IACO",
    "IACQ",
    "IAE",
    "IAF",
    "IAG",
    "IART",
    "IAU",
    "IAUM",
    "IAUX",
    "IBAC",
    "IBCP",
    "IBEX",
    "IBG",
    "IBIO",
    "IBIT",
    "IBKR",
    "IBL",
    "IBM",
    "IBN",
    "IBO",
    "IBOC",
    "IBP",
    "IBRX",
    "IBTA",
    "ICCC",
    "ICCM",
    "ICE",
    "ICFI",
    "ICG",
    "ICHR",
    "ICL",
    "ICLR",
    "ICMB",
    "ICON",
    "ICRL",
    "ICRP",
    "ICU",
    "ICUI",
    "IDA",
    "IDAC",
    "IDAI",
    "IDCC",
    "IDE",
    "IDIA",
    "IDN",
    "IDR",
    "IDT",
    "IDXG",
    "IDXX",
    "IDYA",
    "IE",
    "IEAG",
    "IEHC",
    "IEP",
    "IESC",
    "IEX",
    "IFBD",
    "IFED",
    "IFF",
    "IFN",
    "IFRX",
    "IFS",
    "IGA",
    "IGAC",
    "IGC",
    "IGD",
    "IGI",
    "IGIC",
    "IGR",
    "IH",
    "IHD",
    "IHG",
    "IHRT",
    "IHS",
    "IHT",
    "IIF",
    "III",
    "IIIN",
    "IIIV",
    "IIM",
    "IIPR",
    "IKT",
    "ILAG",
    "ILAL",
    "ILLR",
    "ILLU",
    "ILMN",
    "ILPT",
    "ILXP",
    "IMA",
    "IMAA",
    "IMAQ",
    "IMAX",
    "IMC",
    "IMCC",
    "IMCR",
    "IMDX",
    "IMMP",
    "IMMR",
    "IMMX",
    "IMNM",
    "IMNN",
    "IMO",
    "IMOS",
    "IMPP",
    "IMRN",
    "IMRX",
    "IMSR",
    "IMTE",
    "IMTX",
    "IMUX",
    "IMVT",
    "IMXI",
    "INAB",
    "INAC",
    "INBK",
    "INBP",
    "INBS",
    "INBX",
    "INCR",
    "INCY",
    "INDB",
    "INDI",
    "INDO",
    "INDP",
    "INDV",
    "INEO",
    "INFQ",
    "INFU",
    "INFY",
    "ING",
    "INGM",
    "INGN",
    "INGR",
    "INHD",
    "INHI",
    "ININ",
    "INIO",
    "INIS",
    "INKT",
    "INLF",
    "INLX",
    "INM",
    "INMB",
    "INMD",
    "INN",
    "INNI",
    "INNV",
    "INO",
    "INOD",
    "INR",
    "INRE",
    "INSE",
    "INSG",
    "INSM",
    "INSP",
    "INSW",
    "INTA",
    "INTC",
    "INTG",
    "INTI",
    "INTJ",
    "INTR",
    "INTS",
    "INTT",
    "INTU",
    "INTZ",
    "INUV",
    "INV",
    "INVA",
    "INVE",
    "INVH",
    "INVU",
    "INVX",
    "INVZ",
    "IOND",
    "IONI",
    "IONQ",
    "IONR",
    "IONS",
    "IOR",
    "IOSP",
    "IOT",
    "IOTR",
    "IOVA",
    "IP",
    "IPAR",
    "IPB",
    "IPCX",
    "IPDN",
    "IPEX",
    "IPFX",
    "IPGP",
    "IPHA",
    "IPI",
    "IPM",
    "IPSC",
    "IPSI",
    "IPST",
    "IPVV",
    "IPW",
    "IPWR",
    "IPX",
    "IQ",
    "IQI",
    "IQMX",
    "IQST",
    "IQV",
    "IR",
    "IRAB",
    "IRD",
    "IRDM",
    "IREN",
    "IRHO",
    "IRIX",
    "IRM",
    "IRMD",
    "IRON",
    "IRS",
    "IRT",
    "IRTC",
    "IRWD",
    "ISBA",
    "ISCO",
    "ISD",
    "ISNR",
    "ISOU",
    "ISPC",
    "ISPR",
    "ISRG",
    "ISSC",
    "ISTR",
    "IT",
    "ITG",
    "ITGR",
    "ITHA",
    "ITHR",
    "ITIC",
    "ITOC",
    "ITOX",
    "ITP",
    "ITRE",
    "ITRG",
    "ITRI",
    "ITRN",
    "ITT",
    "ITUB",
    "ITW",
    "ITXP",
    "IVA",
    "IVDA",
    "IVDN",
    "IVF",
    "IVFH",
    "IVHI",
    "IVR",
    "IVT",
    "IVVD",
    "IVZ",
    "IWAL",
    "IWDL",
    "IWFL",
    "IWM",
    "IWML",
    "IWSH",
    "IX",
    "IXHL",
    "IZEA",
    "IZM",
    "J",
    "JAB",
    "JACK",
    "JACS",
    "JAGU",
    "JAGX",
    "JAKK",
    "JAN",
    "JANL",
    "JANX",
    "JATT",
    "JAZZ",
    "JBDI",
    "JBGS",
    "JBHT",
    "JBI",
    "JBIO",
    "JBK",
    "JBL",
    "JBLU",
    "JBS",
    "JBSS",
    "JBTM"
]
"""
Russell 1000 유니버스 (동적 + 캐시)
====================================
1000대 미국 대형주에서 스크리닝합니다.
- 위키피디아 S&P500 + Russell 1000 ETF(IWB) 기반
- 로컬 캐시 (1주일 유효)
- 거래소 자동 매핑
"""

import json
import os
from datetime import datetime, timedelta
from pathlib import Path
from loguru import logger

# ==============================================
# 캐시 설정
# ==============================================

CACHE_FILE = Path(__file__).parent / "universe_cache.json"
CACHE_DAYS = 30  # 3,500+ 전종목 캐시 유지

# ==============================================
# 거래소 매핑 (주요 종목)
# ==============================================

NYSE_SYMBOLS = {
    "JPM", "BAC", "WFC", "GS", "MS", "C", "BK", "USB", "PNC", "TFC",
    "WMT", "HD", "LOW", "TGT", "COST", "DG", "DLTR",
    "JNJ", "PFE", "UNH", "ABT", "TMO", "DHR", "BMY", "LLY", "MRK",
    "XOM", "CVX", "COP", "SLB", "EOG", "MPC", "VLO", "PSX",
    "DIS", "NKE", "MCD", "SBUX", "YUM", "CMG",
    "KO", "PEP", "PG", "CL", "KMB", "EL", "GIS", "K", "SJM",
    "V", "MA", "AXP", "COF", "DFS", "SYF",
    "BA", "RTX", "LMT", "NOC", "GD", "GE", "HON", "MMM", "CAT", "DE",
    "SPY", "IWM", "DIA", "XLK", "XLP", "XLU", "XLV", "XLY", "XLE", "XLF",
    "T", "VZ", "SO", "DUK", "NEE", "AEP", "D", "SRE",
    "BRK.B", "BRK-B", "BLK", "SCHW", "ICE", "CME", "SPGI", "MCO",
    "CRM", "IBM", "ACN", "ORCL",
    "F", "GM",
    "PLD", "AMT", "CCI", "EQIX", "PSA", "SPG",
    "UNP", "CSX", "NSC", "FDX", "UPS",
    # 자주 오류 나는 종목 (NYSE지만 NASD로 기본값 설정 방지)
    "AME", "AIZ", "IRM", "NUE", "RS", "NUE", "FCX", "DD", "DOW",
    "ETN", "EMR", "ITW", "PH", "ROP", "CMI", "DOV", "URI", "PCAR",
    "LIN", "SHW", "APD", "ECL", "VMC", "MLM",
    "WM", "RSG", "AVB", "EQR", "EXR", "MAA", "UDR", "INVH", "CPT",
    "WELL", "VTR", "ARE", "O", "VTR",
}

AMEX_SYMBOLS = {"SQQQ", "TQQQ", "UVXY", "VXX"}


def get_exchange(symbol: str) -> str:
    """종목의 거래소 코드 반환 (주문용)"""
    s = symbol.upper().replace(".", "")
    if s in AMEX_SYMBOLS:
        return "AMEX"
    if s in NYSE_SYMBOLS:
        return "NYSE"
    return "NASD"  # Default — NASDAQ


# ==============================================
# Russell 1000 동적 로딩
# ==============================================

def _fetch_sp500_from_wikipedia() -> list:
    """S&P 500 구성종목 반환.

    Oracle Cloud VM은 Wikipedia에서 HTTP 403으로 차단되므로
    완전한 정적 목록을 하드코딩 (2025년 기준 S&P 500).
    네트워크 fetch 먼저 시도, 실패 시 정적 목록 사용.
    """
    # ── 완전한 S&P 500 정적 목록 (Wikipedia 차단 대비 fallback) ──────────────
    # ★ [v3.3.0 100% DYNAMIC MARKET LEADER ENGINE]
    # Screener dynamically ranks candidate stocks by real-time RS (1M+3M+6M+RVOL) on every single run.
    SP500_STATIC = [
        "A", "AAL", "AAPL", "ABBV", "ABNB", "ABT", "ACGL", "ACN", "ADBE", "ADI", "ADM",
        "ADP", "ADSK", "AEE", "AEP", "AES", "AFL", "AIG", "AIZ", "AJG", "AKAM",
        "ALB", "ALGN", "ALL", "ALLE", "AMAT", "AMCR", "AME", "AMGN", "AMP",
        "AMT", "ANET", "AON", "AOS", "APA", "APD", "APH", "APO", "APP",
        "APTV", "ARE", "ARES", "ATO", "AVB", "AVY", "AWK", "AXON", "AXP",
        "AZO", "BA", "BAC", "BALL", "BAX", "BBY", "BDX", "BEN", "BFB", "BG",
        "BIIB", "BKNG", "BKR", "BLDR", "BLK", "BMY", "BNY", "BR", "BRK-B", "BRO",
        "BSX", "BX", "BXP", "C", "CAG", "CAH", "CARR", "CASY", "CAT", "CB",
        "CBOE", "CBRE", "CCI", "CCL", "CDNS", "CDW", "CEG", "CF", "CFG", "CHD",
        "CHRW", "CHTR", "CI", "CIEN", "CINF", "CL", "CLX", "CMCSA", "CME", "CMG",
        "CMI", "CMS", "CNC", "CNP", "COF", "COHR", "COIN", "COO", "COP", "COR",
        "COST", "CPAY", "CPB", "CPRT", "CPT", "CRH", "CRL", "CRM", "CRWD", "CSCO",
        "CSGP", "CSX", "CTAS", "CTSH", "CTVA", "CVNA", "CVS", "CVX", "D", "DAL",
        "DASH", "DD", "DDOG", "DE", "DECK", "DELL", "DG", "DGX", "DHI", "DHR",
        "DIS", "DLR", "DLTR", "DOC", "DOV", "DOW", "DPZ", "DRI", "DTE", "DUK",
        "DVA", "DVN", "DXCM", "EA", "EBAY", "ECL", "ED", "EFX", "EG", "EIX",
        "EL", "ELV", "EME", "EMR", "EOG", "EPAM", "EQIX", "EQR", "EQT", "ERIE",
        "ES", "ESS", "ETN", "ETR", "EVRG", "EW", "EXC", "EXE", "EXPD", "EXPE",
        "EXR", "F", "FANG", "FAST", "FCX", "FDS", "FDX", "FE", "FFIV", "FICO",
        "FIS", "FISV", "FITB", "FIX", "FOX", "FOXA", "FRT", "FSLR", "FTNT", "FTV",
        "GD", "GDDY", "GE", "GEHC", "GEN", "GEV", "GILD", "GIS", "GL", "GLW",
        "GM", "GNRC", "GOOG", "GOOGL", "GPC", "GPN", "GRMN", "GS", "GWW", "HAL",
        "HAS", "HBAN", "HCA", "HD", "HIG", "HII", "HLT", "HON", "HOOD", "HPE",
        "HPQ", "HRL", "HSIC", "HST", "HSY", "HUBB", "HUM", "HWM", "IBKR", "IBM",
        "ICE", "IDXX", "IEX", "IFF", "INCY", "INTC", "INTU", "INVH", "IP", "IQV",
        "IR", "IRM", "ISRG", "IT", "ITW", "IVZ", "J", "JBHT", "JBL", "JCI",
        "JKHY", "JNJ", "JPM", "KDP", "KEY", "KEYS", "KHC", "KIM", "KKR", "KLAC",
        "KMB", "KMI", "KO", "KR", "KVUE", "L", "LDOS", "LEN", "LH", "LHX",
        "LII", "LIN", "LITE", "LLY", "LMT", "LNT", "LOW", "LRCX", "LULU", "LUV",
        "LVS", "LYB", "LYV", "MA", "MAA", "MAR", "MAS", "MCD", "MCHP", "MCK",
        "MCO", "MDLZ", "MDT", "MET", "META", "MGM", "MKC", "MLM", "MMM", "MNST",
        "MO", "MOS", "MPC", "MPWR", "MRK", "MRNA", "MRSH", "MS", "MSCI", "MSFT",
        "MSI", "MTB", "MTD", "MU", "NCLH", "NDAQ", "NDSN", "NEE", "NEM", "NFLX",
        "NI", "NKE", "NOC", "NOW", "NRG", "NSC", "NTAP", "NTRS", "NUE", "NVDA",
        "NVR", "NWS", "NWSA", "NXPI", "O", "ODFL", "OKE", "OMC", "ON", "ORCL",
        "ORLY", "OTIS", "OXY", "PANW", "PAYX", "PCAR", "PCG", "PEG", "PEP", "PFE",
        "PFG", "PG", "PGR", "PH", "PHM", "PKG", "PLD", "PLTR", "PM", "PNC",
        "PNR", "PNW", "PODD", "POOL", "PPG", "PPL", "PRU", "PSA", "PSKY", "PSX",
        "PTC", "PWR", "PYPL", "Q", "QCOM", "RCL", "REG", "REGN", "RF", "RJF",
        "RL", "RMD", "ROK", "ROL", "ROP", "ROST", "RSG", "RTX", "RVTY", "SATS",
        "SBAC", "SBUX", "SCHW", "SHW", "SJM", "SLB", "SMCI", "SNA", "SNDK", "SNPS",
        "SO", "SOLV", "SPG", "SPGI", "SRE", "STE", "STLD", "STT", "STX", "STZ",
        "SW", "SWK", "SWKS", "SYF", "SYK", "SYY", "T", "TAP", "TDG", "TDY",
        "TECH", "TEL", "TER", "TFC", "TGT", "TJX", "TKO", "TMO", "TMUS", "TPL",
        "TPR", "TRGP", "TRMB", "TROW", "TRV", "TSCO", "TSLA", "TSN", "TT", "TTD",
        "TTWO", "TXN", "TXT", "TYL", "UAL", "UBER", "UDR", "UHS", "ULTA", "UNH",
        "UNP", "UPS", "URI", "USB", "V", "VEEV", "VICI", "VLO", "VLTO", "VMC",
        "VRSK", "VRSN", "VRT", "VRTX", "VST", "VTR", "VTRS", "VZ", "WAB", "WAT",
        "WBD", "WDAY", "WDC", "WEC", "WELL", "WFC", "WM", "WMB", "WMT", "WRB",
        "WSM", "WST", "WTW", "WY", "WYNN", "XEL", "XOM", "XYL", "XYZ", "YUM",
        "ZBH", "ZBRA", "ZTS",
    ]

    # 1) 네트워크 fetch 시도 (성공하면 최신 목록 우선)
    try:
        import pandas as pd
        import urllib.request
        req = urllib.request.Request(
            "https://en.wikipedia.org/wiki/List_of_S%26P_500_companies",
            headers={"User-Agent": "Mozilla/5.0 (compatible; trading-bot/1.0)"}
        )
        html = urllib.request.urlopen(req, timeout=10).read()
        import io
        tables = pd.read_html(io.BytesIO(html))
        df = tables[0]
        symbols = df["Symbol"].str.replace(".", "", regex=False).tolist()
        if len(symbols) > 400:
            logger.info("S&P 500: {} symbols from Wikipedia (live)", len(symbols))
            return symbols
    except Exception as e:
        logger.warning("Wikipedia S&P500 fetch failed (using static list): {}", e)

    # 2) 정적 목록 사용
    logger.info("S&P 500: {} symbols from static list", len(SP500_STATIC))
    return SP500_STATIC


def _fetch_russell1000_tickers() -> list:
    """Russell 1000 구성종목 가져오기 (S&P500 + 추가 대형주)"""
    symbols = set()
    
    # 1) S&P 500 (핵심)
    sp500 = _fetch_sp500_from_wikipedia()
    symbols.update(sp500)
    
    # 2) Russell 1000 중 S&P500에 없는 주요 종목 추가
    additional_russell = [
        "AA", "AAL", "AAMI", "AAON", "AAP", "AAT", "ABCB", "ABG", "ABM", "ABR",
        "ACA", "ACAD", "ACHC", "ACI", "ACIW", "ACLS", "ACM", "ACMR", "ACT", "ADAM",
        "ADC", "ADEA", "ADMA", "ADNT", "ADT", "ADUS", "AEIS", "AEO", "AESI", "AFG",
        "AFRM", "AGCO", "AGNT", "AGO", "AGX", "AGYS", "AHCO", "AHR", "AIN", "AIR",
        "AIT", "AKR", "ALG", "ALGM", "ALGT", "ALHC", "ALK", "ALKS", "ALLY", "ALRM",
        "ALV", "AM", "AMG", "AMH", "AMKR", "AMN", "AMPH", "AMR", "AMRX", "AMSF",
        "AMTM", "AMWD", "AN", "ANDE", "ANF", "ANIP", "AORT", "AOSL", "APAM", "APG",
        "APLE", "APOG", "APPF", "AR", "ARCB", "ARI", "ARLO", "ARMK", "AROC", "ARR",
        "ARW", "ARWR", "ASB", "ASH", "ASO", "ASTE", "ASTH", "ASTS", "ATEN", "ATI",
        "ATMU", "ATR", "AUB", "AVA", "AVAV", "AVNS", "AVNT", "AVT", "AVTR", "AWI",
        "AWR", "AX", "AXTA", "AYI", "AZTA", "AZZ", "BAH", "BANC", "BANF", "BANR",
        "BBT", "BBWI", "BC", "BCC", "BCO", "BCPC", "BDC", "BFAM", "BFH", "BFS",
        "BGC", "BHE", "BHF", "BILL", "BIO", "BJ", "BJRI", "BKE", "BKH", "BKU",
        "BL", "BLD", "BLFS", "BLKB", "BMI", "BMRN", "BNL", "BOH", "BOOT", "BOX",
        "BRBR", "BRC", "BRKR", "BROS", "BRX", "BSY", "BTSG", "BTU", "BURL", "BWA",
        "BWXT", "BXMT", "BYD", "CABO", "CACI", "CAKE", "CALM", "CALX", "CALY", "CAR",
        "CARG", "CART", "CASH", "CATY", "CAVA", "CBRL", "CBSH", "CBT", "CBU", "CC",
        "CCK", "CCOI", "CCS", "CDP", "CE", "CELH", "CENT", "CENTA", "CENX", "CERT",
        "CFFN", "CFLT", "CFR", "CG", "CGNX", "CHCO", "CHDN", "CHE", "CHEF", "CHH",
        "CHRD", "CHWY", "CLB", "CLF", "CLH", "CLSK", "CMC", "CNH", "CNK", "CNM",
        "CNMD", "CNO", "CNR", "CNS", "CNX", "CNXC", "CNXN", "COCO", "COHU", "COKE",
        "COLB", "COLL", "COLM", "CON", "CORT", "COTY", "CPF", "CPK", "CPNG", "CPRI",
        "CPRX", "CR", "CRBG", "CRC", "CRGY", "CRI", "CRK", "CROX", "CRS", "CRSR",
        "CRUS", "CRVL", "CSL", "CSR", "CSW", "CTKB", "CTRE", "CTS", "CUBE", "CUBI",
        "CURB", "CUZ", "CVBF", "CVCO", "CVI", "CVLT", "CVSA", "CW", "CWEN", "CWENA",
        "CWK", "CWST", "CWT", "CXM", "CXT", "CXW", "CYTK", "CZR", "DAN", "DAR",
        "DBD", "DBX", "DCH", "DCI", "DCOM", "DEA", "DEI", "DFH", "DFIN", "DGII",
        "DINO", "DIOD", "DKS", "DLB", "DLX", "DNOW", "DOCN", "DOCS", "DOCU", "DORM",
        "DRH", "DT", "DTM", "DUOL", "DV", "DXC", "DXPE", "DY", "EAT", "ECG",
        "ECPG", "EEFT", "EFC", "EFOR", "EGBN", "EGP", "EHC", "EIG", "ELAN", "ELF",
        "ELS", "EMBC", "EMN", "ENOV", "ENPH", "ENR", "ENS", "ENSG", "ENTG", "ENVA",
        "EPAC", "EPC", "EPR", "EPRT", "EQH", "ESAB", "ESE", "ESI", "ESNT", "ETD",
        "ETSY", "EVR", "EVTC", "EWBC", "EXEL", "EXLS", "EXP", "EXPO", "EXTR", "EYE",
        "EZPW", "FAF", "FBIN", "FBK", "FBNC", "FBP", "FBRT", "FCF", "FCFS", "FCN",
        "FCPT", "FDP", "FELE", "FFBC", "FFIN", "FG", "FHB", "FHI", "FHN", "FIBK",
        "FIVE", "FIZZ", "FLEX", "FLG", "FLO", "FLR", "FLS", "FMC", "FN", "FNB",
        "FND", "FNF", "FORM", "FOUR", "FOXF", "FR", "FRPT", "FSS", "FTDR", "FTI",
        "FTRE", "FUL", "FULT", "FUN", "FWRD", "G", "GAP", "GATX", "GBCI", "GBX",
        "GDYN", "GEF", "GEO", "GFF", "GGG", "GHC", "GIII", "GKOS", "GLPI", "GME",
        "GMED", "GNL", "GNTX", "GNW", "GO", "GOGO", "GOLF", "GPI", "GPK", "GRBK",
        "GSHD", "GT", "GTES", "GTLS", "GTM", "GTY", "GVA", "GWRE", "GXO", "H",
        "HAE", "HAFC", "HALO", "HASI", "HAYW", "HCC", "HCI", "HCSG", "HE", "HFWA",
        "HGV", "HIMS", "HIW", "HL", "HLI", "HLIT", "HLNE", "HLX", "HMN", "HNI",
        "HOG", "HOMB", "HOPE", "HQY", "HR", "HRB", "HWC", "HXL", "IBOC", "IDA",
        "IDCC", "ILMN", "INGR", "IPGP", "IRT", "ITT", "JAZZ", "JEF", "JHG", "JLL",
        "KBH", "KBR", "KD", "KEX", "KNF", "KNSL", "KNX", "KRC", "KRG", "KTOS",
        "LAD", "LAMR", "LCID", "LEA", "LECO", "LFUS", "LIVN", "LNTH", "LOPE", "LPX",
        "LSCC", "LSTR", "M", "MANH", "MASI", "MAT", "MDB", "MEDP", "MELI", "MIDD",
        "MKSI", "MLI", "MMS", "MOGA", "MORN", "MP", "MSA", "MSM", "MSTR", "MTDR",
        "MTG", "MTN", "MTSI", "MTZ", "MUR", "MUSA", "MZTI", "NBIX", "NET", "NEU",
        "NFG", "NJR", "NLY", "NNN", "NOV", "NOVT", "NSA", "NTNX", "NVST", "NVT",
        "NWE", "NXST", "NXT", "NYT", "OC", "OGE", "OGS", "OHI", "OKTA", "OLED",
        "OLLI", "OLN", "ONB", "ONTO", "OPCH", "ORA", "ORI", "OSK", "OVV", "OZK",
        "P", "PAG", "PATH", "PB", "PBF", "PCTY", "PEGA", "PEN", "PFGC", "PII",
        "PINS", "PK", "PLNT", "PNFP", "POR", "POST", "PPC", "PR", "PRI", "PSN",
        "PVH", "QLYS", "QS", "R", "RBA", "RBC", "REXR", "RGA", "RGEN", "RGLD",
        "RH", "RIVN", "RKLB", "RLI", "RMBS", "RNR", "ROIV", "RPM", "RRC", "RRX",
        "RS", "RYAN", "RYN", "SAIA", "SAIC", "SAM", "SARO", "SBRA", "SCI", "SE",
        "SEIC", "SF", "SFM", "SGI", "SHC", "SHOP", "SIGI", "SITM", "SLAB", "SLGN",
        "SLM", "SMG", "SN", "SNOW", "SNX", "SOFI", "SOLS", "SON", "SPXC", "SR",
        "SSB", "SSD", "ST", "STAG", "STRL", "STWD", "SWX", "SYNA", "TCBI", "TEX",
        "THC", "THG", "THO", "TKR", "TLN", "TMHC", "TNL", "TOL", "TREX", "TRU",
        "TTC", "TTEK", "TTMI", "TWLO", "TXNM", "TXRH", "UBSI", "UFPI", "UGI", "ULS",
        "UMBF", "UNM", "USFD", "UTHR", "VAL", "VC", "VFC", "VICR", "VLY", "VMI",
        "VNO", "VNOM", "VNT", "VOYA", "VVV", "WAL", "WBS", "WCC", "WEX", "WFRD",
        "WH", "WHR", "WING", "WLK", "WMG", "WMS", "WPC", "WSO", "WTFC", "WTRG",
        "WTS", "WWD", "XPO", "XRAY", "YETI", "ZION", "ZS",
    ]
    symbols.update(additional_russell)
    
    # 중복/빈값 제거 & 정렬
    symbols = sorted([s.strip() for s in symbols if s and s.strip()])
    
    # 마침표가 있는 심볼을 KIS API 형식으로 변환 (BRK.B -> BRKB)
    cleaned = []
    for s in symbols:
        clean = s.replace(".", "").replace("-", "")
        if clean and len(clean) <= 5:  # 합리적 길이
            cleaned.append(clean)
        else:
            cleaned.append(s.replace(".", "").replace("-", "")[:5])
    
    # 중복 제거
    cleaned = sorted(set(cleaned))
    
    logger.info("Russell 1000 universe: {} symbols", len(cleaned))
    return cleaned


# ==============================================
# 캐시 관리
# ==============================================

def _save_cache(symbols: list):
    """유니버스 캐시 저장"""
    data = {
        "updated": datetime.now().isoformat(),
        "count": len(symbols),
        "symbols": symbols
    }
    with open(CACHE_FILE, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
    logger.info("Universe cache saved: {} symbols", len(symbols))


def _load_cache() -> list:
    """유니버스 캐시 로드 (3,500+ 전종목 100% 보장)"""
    if not CACHE_FILE.exists():
        return []
    try:
        with open(CACHE_FILE, "r", encoding="utf-8") as f:
            data = json.load(f)
        if isinstance(data, list):
            logger.info("Universe loaded from cache (list format): {} symbols", len(data))
            return data
        elif isinstance(data, dict) and "symbols" in data:
            syms = data["symbols"]
            logger.info("Universe loaded from cache: {} symbols", len(syms))
            return syms
        return []
    except Exception as e:
        logger.warning("Cache load failed: {}", e)
        return []


# ==============================================
# 핵심 유니버스 (네트워크 차단 시 폴백) & 빅테크/우량주 백업 리스트
# ==============================================

CORE_UNIVERSE = [
    # Mega Cap Tech (빅테크)
    "AAPL", "MSFT", "GOOGL", "AMZN", "NVDA", "META", "TSLA", "AVGO", "ORCL", "CRM",
    # Semiconductor (반도체)
    "AMD", "INTC", "QCOM", "TXN", "MU", "LRCX", "KLAC", "AMAT", "MRVL", "SMCI", "ARM", "ASML", "TSM",
    "ON", "LSCC", "MPWR", "AMKR", "MCHP",
    # Software / Cloud (클라우드/소프트웨어)
    "ADBE", "NOW", "INTU", "SNOW", "PLTR", "NET", "CRWD", "DDOG", "ZS", "PANW", "FTNT", "WDAY", "TEAM",
    "VEEV", "ANET", "CDNS", "SNPS", "TYL", "PTC", "EPAM", "IT",
    # AI / Quantum (신성장)
    "IONQ", "RGTI", "APP", "PATH", "TTD", "ROKU",
    # E-commerce / Consumer (이커머스/컨슈머 테크)
    "SHOP", "MELI", "BKNG", "ABNB", "CPNG", "NFLX", "SPOT", "UBER", "DASH",
    # Fintech / Crypto (핀테크/크립토)
    "COIN", "MSTR", "SOFI", "HOOD", "AFRM", "SQ", "PYPL",
    
    # === 방어주 & 전통 우량주 확장 (시장이 불안정할 때 피난처) ===
    # Healthcare / Pharma (헬스케어/제약)
    "LLY", "UNH", "JNJ", "ABBV", "MRK", "PFE", "TMO", "ABT", "ISRG", "DXCM", "DHR", "SYK", "VRTX", "REGN", "AMGN",
    "HUM", "CI", "CNC", "ZTS", "IDXX", "EW", "BDX", "BSX", "MTD", "ILMN", "BIIB", "MCK", "COR", "ZBH",
    # Finance / Banks (금융/은행)
    "JPM", "BAC", "GS", "MS", "V", "MA", "BRK-B", "WFC", "C", "AXP", "BLK", "SCHW", "SPGI", "CME",
    "PGR", "CB", "MMC", "AON", "TRV", "ALL", "AFL", "MET", "PRU", "COF", "DFS", "SYF", "TFC", "USB",
    # Industrial / Defense (산업재/방산 - 지정학적 리스크 헷지)
    "CAT", "DE", "BA", "GE", "HON", "RTX", "LMT", "NOC", "GD", "TDG", "WM", "RSG",
    "UNP", "UPS", "FDX", "CSX", "NSC", "ETN", "EMR", "ITW", "PH", "ROP", "CMI", "DOV", "URI", "PCAR",
    # Consumer Discretionary & Staples (소비재 - 경기 침체 방어)
    "WMT", "COST", "HD", "NKE", "MCD", "SBUX", "KO", "PEP", "PG", "PM", "MO", "TGT", "CL", "KMB",
    "TJX", "ROST", "LULU", "ORLY", "AZO", "TSCO", "YUM", "DRI", "HLT", "MAR", "CMG", "DG", "DLTR", "K", "GIS",
    # Energy (에너지/정유 - 인플레이션 헷지)
    "XOM", "CVX", "COP", "SLB", "EOG", "MPC", "VLO", "PSX", "OXY",
    "HES", "FANG", "DVN", "PXD", "HAL", "BKR", "WMB", "KMI", "OKE",
    # Utilities & Telecom (유틸리티/통신 - 고배당/안전가치)
    "NEE", "DUK", "SO", "AEP", "SRE", "T", "VZ", "TMUS", "EXC", "XEL", "ED", "PEG", "WEC", "AWK",
    # Real Estate / REITs (리츠)
    "PLD", "AMT", "EQIX", "CCI", "PSA", "O",
    "SPG", "AVB", "EQR", "EXR", "MAA", "UDR", "INVH", "CPT", "WELL", "VTR", "ARE",
    # Materials / Commodity
    "LIN", "SHW", "APD", "ECL", "NUE", "FCX", "STLD", "VMC", "MLM", "CTVA",
    
    # Space / Defense
    "RKLB", "AXON", "KTOS",
    # Biotech
    "MRNA", "CRSP", "BEAM",
]

# 위 Fallback(CORE) 유니버스 종목인지 판별하기 위한 세트
FALLBACK_SYMBOLS = set(CORE_UNIVERSE)


# ==============================================
# Public API
# ==============================================

_universe_cache = None

def get_all_symbols() -> list:
    """전체 유니버스 종목 리스트 반환 (캐시 적용)"""
    global _universe_cache
    
    if _universe_cache:
        return _universe_cache.copy()
    
    # 1) 로컬 캐시
    symbols = _load_cache()
    
    # 2) 동적 로딩
    if not symbols:
        try:
            symbols = _fetch_russell1000_tickers()
            if symbols and len(symbols) > 100:
                _save_cache(symbols)
        except Exception as e:
            logger.error("Dynamic fetch failed: {}", e)
    
    # 3) 폴백
    if not symbols or len(symbols) < 50000000000000:
        logger.warning("Using core universe fallback ({} symbols)", len(CORE_UNIVERSE))
        symbols = MASTER_3500_UNIVERSE.copy()
    
    _universe_cache = symbols
    
    # Filter out KIS API permanently blacklisted symbols
    try:
        bl_path = Path("kis_symbol_blacklist.json")
        if bl_path.exists():
            import json as _json
            bl_data = _json.loads(bl_path.read_text(encoding="utf-8"))
            blacklist = set(bl_data.get("symbols", []))
            if blacklist:
                before = len(_universe_cache)
                _universe_cache = [s for s in _universe_cache if s.upper() not in blacklist]
                removed = before - len(_universe_cache)
                if removed > 0:
                    logger.info("Universe: filtered {} KIS-blacklisted symbols (remaining: {})",
                               removed, len(_universe_cache))
    except Exception as e:
        logger.debug("Blacklist filter failed: {}", e)
    
    return _universe_cache.copy()


def get_symbol_info(symbol: str) -> dict:
    """종목 정보 반환"""
    return {
        "name": symbol,
        "exchange": get_exchange(symbol),
        "sector": "",
    }


def get_universe_count() -> int:
    """유니버스 종목 수"""
    return len(get_all_symbols())


def refresh_universe():
    """유니버스 강제 갱신"""
    global _universe_cache
    _universe_cache = None
    if CACHE_FILE.exists():
        CACHE_FILE.unlink()
    symbols = get_all_symbols()
    logger.info("Universe refreshed: {} symbols", len(symbols))
    return symbols


if __name__ == "__main__":
    import sys
    logger.remove()
    logger.add(sys.stderr, level="INFO", colorize=True,
               format="<green>{time:HH:mm:ss}</green> | <level>{message}</level>")
    
    print("=" * 50)
    print("📊 Russell 1000 유니버스")
    print("=" * 50)
    
    symbols = get_all_symbols()
    print(f"\n총 {len(symbols)}개 종목")
    print(f"\n처음 20개: {symbols[:20]}")
    print(f"마지막 10개: {symbols[-10:]}")
    
    # 거래소 분포
    exchanges = {}
    for s in symbols:
        ex = get_exchange(s)
        exchanges[ex] = exchanges.get(ex, 0) + 1
    print(f"\n거래소 분포: {exchanges}")
